import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Footer from './Components/Footer'
import Header from './Components/Header'
import Main from './Components/Main'
import Second from './Components/Second'

export default function Home() {
  return (
    <div >
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
    <div className='bg-white ' >
      {/* <div className='fixed  flex justify-between w-full h-full '>

      <div className='w-[1px] xl:-[7%] -[9%] bg-[#E5E7EB] h-full   '></div>
      <div className='w-[1px] z-0 bg-[#E5E7EB] h-full   -1/4 '></div>
      <div className='w-[1px] z-0 bg-[#E5E7EB] h-full   -1/2 '></div>
      <div className='w-[1px] z-0 bg-[#E5E7EB] h-full   -3/4 '></div>
      <div className='w-[1px] bg-[#E5E7EB] h-full   -[5%] '></div>

      </div> */}
    <Header/>
    <Main/>
    <Second/>
    {/* <Footer/> */}

    </div>
      
    </div>
  )
}
