import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Header from './Components/Header'
import Main from './Components/Main'
import Second from './Components/Second'

export default function Home() {
  return (
    <div >
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
    <div className='bg-white ' >
      {/* <div className='w-[1px] bg-[#E5E7EB] h-[100vh] absolute left-[7%] '></div>
      <div className='w-[1px] z-0 bg-[#E5E7EB] h-[100vh] absolute left-1/4 '></div>
      <div className='w-[1px] z-0 bg-[#E5E7EB] h-[100vh] absolute left-1/2 '></div>
      <div className='w-[1px] z-0 bg-[#E5E7EB] h-[100vh] absolute left-3/4 '></div>
      <div className='w-[1px] bg-[#E5E7EB] h-[100vh] absolute right-[5%] '></div> */}

    <Header/>
    <Main/>
    <Second/>

    </div>
      
    </div>
  )
}
